from django import forms
from funcionarios.models import Funcionarios


SEXO_CHOICES = [("M", "Masculino"), ("F", "Feminino")]
ESTADO_CIVIL_CHOICES = [
    ("S", "Solteiro(a)"),
    ("C", "Casado(a)"),
    ("D", "Divorciado(a)"),
    ("V", "Viúvo(a)"),
    ("U", "União Estável"),
]
FOPA_CHOICES = [
    ("M", "Mensal"),
    ("S", "Semanal"),
    ("Q", "Quinzenal"),
    ("D", "Diário"),
]


def _ctrl(placeholder=None, extra=None):
    attrs = {"class": "form-control"}
    if placeholder:
        attrs["placeholder"] = placeholder
    if extra:
        attrs.update(extra)
    return attrs


def _check():
    return {"class": "form-check-input"}


class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionarios
        fields = [
            # --- Identificação ---
            "func_empr", "func_fili", "func_codi", "func_regi",
            "func_nome", "func_sexo", "func_dana", "func_cpf", "func_pis",
            "func_esci", "func_naci", "func_raca", "func_vinc",
            "func_natu", "func_uf_natu", "func_pais_nasc", "func_pais_naci",
            "func_emai", "func_celu", "func_fone_dive",
            "func_inat", "func_apre",
            # --- Endereço ---
            "func_tipo_logr", "func_ende", "func_bair", "func_cep",
            "func_esta", "func_ibge", "func_loca", "func_loca_uf",
            # --- Vínculo Empregatício ---
            "func_depa", "func_seto", "func_carg", "func_catr",
            "func_daad", "func_tiad", "func_demi", "func_tide",
            "func_fopa", "func_tisa", "func_tisa_rais",
            "func_cbo", "func_grin", "func_cose",
            "func_sind", "func_func_sind", "func_refe_desc_sind",
            "func_tipo_cont", "func_data_term_cont",
            "func_esoc_tipo_admi", "func_esoc_indi_admi",
            "func_natu_ativ", "func_cate_esoc", "func_cate_sefi",
            "func_ocor_sefi", "func_matr", "func_norm",
            "func_jorn", "func_esoc_regi_jorn",
            "func_regi_prev", "func_apos",
            "func_tp_rein", "func_num_proc", "func_lei_anis",
            "func_data_efet_reto", "func_data_efeito",
            "func_indi_contr",
            # --- Salário ---
            "func_home", "func_hose", "func_same", "func_saho",
            "func_sala_cont", "func_valo_diar", "func_pens",
            "func_adqu", "func_insa", "func_peri",
            "func_perc_insa", "func_insa_sobr", "func_insa_sobr_valo",
            "func_base_insa",
            "func_alva", "func_vale_alim", "func_vale_trans",
            # --- Banco / Pagamento ---
            "func_banc_paga", "func_agen", "func_cont_paga",
            "func_tipo_cred", "func_cont_fgts", "func_daop_fgts",
            "func_inss", "func_fgts", "func_irrf",
            "func_remu_outr_tpinsc", "func_remu_outr_nrinsc",
            "func_remu_outr_cate", "func_remu_outr_valo", "func_remu_outr_indi",
            # --- Documentos ---
            "func_ctps", "func_seri_ctps", "func_esta_ctps", "func_emis_ctps",
            "func_titu", "func_digi_titu", "func_zona_titu", "func_seca_titu",
            "func_regi_prof", "func_regi_cate", "func_regi_vali",
            "func_rege", "func_rege_orga", "func_rege_expe", "func_rege_uf",
            "func_cnh", "func_cate", "func_cnh_prim", "func_cnh_emis",
            "func_cnh_vali", "func_cnh_esta",
            "func_rne", "func_rne_emis", "func_rne_expe",
            "func_extr_cond", "func_extr_data_cheg",
            "func_extr_casa_bras", "func_extr_filh_bras",
            "func_defi", "func_tipo_defi", "func_defi_cota",
            # --- Jornada ---
            "func_en01", "func_sa01", "func_en02", "func_sa02",
            "func_saba", "func_domi", "func_feri",
            "func_dia1", "func_ven1", "func_dia2", "func_ven2",
            "func_temp_resi",
            # --- Saúde / Exames ---
            "func_venc_exam", "func_exam_data", "func_exam_codi",
            "func_exam_cnpj", "func_exam_crm", "func_exam_crm_uf",
            "func_data_expi_exam_ocup", "func_tipo_exam_ocup",
            # --- Estágio ---
            "func_esta_natu_esta", "func_esta_nive_esta",
            "func_esta_data_term", "func_esta_inst_ensi",
            "func_apren_contr_dire", "func_apren_enti_qual",
            # --- Aprendiz / eSocial ---
            "func_esoc_tipo_insc", "func_esoc_nume_insc",
            "func_esoc_matr_ante", "func_esoc_tran_obse", "func_esoc_data_tran",
            "func_codi_lota_trib",
            "func_cate_tpinsc", "func_cate_nrinsc",
            "func_cons_fgts_inst", "func_cons_fgts_contr", "func_cons_fgts_even",
        ]

        labels = {
            # Identificação
            "func_empr": "Empresa",
            "func_fili": "Filial",
            "func_codi": "Código",
            "func_regi": "Registro",
            "func_nome": "Nome Completo",
            "func_sexo": "Sexo",
            "func_dana": "Data de Nascimento",
            "func_cpf": "CPF",
            "func_pis": "PIS/PASEP",
            "func_esci": "Estado Civil",
            "func_naci": "Nacionalidade",
            "func_raca": "Raça/Cor",
            "func_vinc": "Vínculo",
            "func_natu": "Naturalidade",
            "func_uf_natu": "UF Naturalidade",
            "func_pais_nasc": "País de Nascimento",
            "func_pais_naci": "País de Nacionalidade",
            "func_emai": "E-mail",
            "func_celu": "Celular",
            "func_fone_dive": "Outros Telefones",
            "func_inat": "Inativo",
            "func_apre": "Apresentado",
            # Endereço
            "func_tipo_logr": "Tipo de Logradouro",
            "func_ende": "Endereço",
            "func_bair": "Bairro",
            "func_cep": "CEP",
            "func_esta": "Estado (UF)",
            "func_ibge": "Cód. IBGE",
            "func_loca": "Localidade",
            "func_loca_uf": "UF Localidade",
            # Vínculo
            "func_depa": "Departamento",
            "func_seto": "Setor",
            "func_carg": "Cargo",
            "func_catr": "Categoria Trabalhista",
            "func_daad": "Data de Admissão",
            "func_tiad": "Tipo de Admissão",
            "func_demi": "Data de Demissão",
            "func_tide": "Tipo de Demissão",
            "func_fopa": "Forma de Pagamento",
            "func_tisa": "Tipo de Salário",
            "func_tisa_rais": "Tipo de Salário (RAIS)",
            "func_cbo": "CBO",
            "func_grin": "Grau de Instrução",
            "func_cose": "Código do Serviço",
            "func_sind": "Sindicato",
            "func_func_sind": "Função Sindical",
            "func_refe_desc_sind": "Ref. Desconto Sindicato",
            "func_tipo_cont": "Tipo de Contrato",
            "func_data_term_cont": "Término do Contrato",
            "func_esoc_tipo_admi": "Tipo de Admissão (eSocial)",
            "func_esoc_indi_admi": "Indicativo de Admissão (eSocial)",
            "func_natu_ativ": "Natureza da Atividade",
            "func_cate_esoc": "Categoria eSocial",
            "func_cate_sefi": "Categoria SEFI",
            "func_ocor_sefi": "Ocorrência SEFI",
            "func_matr": "Matrícula",
            "func_norm": "Regime Normal",
            "func_jorn": "Jornada (horas)",
            "func_esoc_regi_jorn": "Regime de Jornada (eSocial)",
            "func_regi_prev": "Regime Previdenciário",
            "func_apos": "Aposentado",
            "func_tp_rein": "Tipo de Reintegração",
            "func_num_proc": "Número do Processo",
            "func_lei_anis": "Lei de Anistia",
            "func_data_efet_reto": "Data Efetiva de Retorno",
            "func_data_efeito": "Data de Efeito",
            "func_indi_contr": "Indicativo do Contrato",
            # Salário
            "func_home": "Horas Mensais",
            "func_hose": "Horas Semanais",
            "func_same": "Salário Mensal",
            "func_saho": "Salário por Hora",
            "func_sala_cont": "Salário Contratual",
            "func_valo_diar": "Valor Diário",
            "func_pens": "Pensão Alimentícia",
            "func_adqu": "Adicional de Qualificação",
            "func_insa": "Insalubridade",
            "func_peri": "Periculosidade",
            "func_perc_insa": "% Insalubridade",
            "func_insa_sobr": "Insalubridade Sobreaviso",
            "func_insa_sobr_valo": "Valor Insalubridade Sobreaviso",
            "func_base_insa": "Base de Cálculo Insalubridade",
            "func_alva": "Alvará",
            "func_vale_alim": "Vale Alimentação",
            "func_vale_trans": "Vale Transporte",
            # Banco / Pagamento
            "func_banc_paga": "Banco para Pagamento",
            "func_agen": "Agência",
            "func_cont_paga": "Conta para Pagamento",
            "func_tipo_cred": "Tipo de Crédito",
            "func_cont_fgts": "Conta FGTS",
            "func_daop_fgts": "Data Opção FGTS",
            "func_inss": "Descontar INSS",
            "func_fgts": "Descontar FGTS",
            "func_irrf": "Descontar IRRF",
            "func_remu_outr_tpinsc": "Tipo Inscrição Outra Remuneração",
            "func_remu_outr_nrinsc": "Nº Inscrição Outra Remuneração",
            "func_remu_outr_cate": "Categoria Outra Remuneração",
            "func_remu_outr_valo": "Valor Outra Remuneração",
            "func_remu_outr_indi": "Indicativo Outra Remuneração",
            # Documentos
            "func_ctps": "CTPS",
            "func_seri_ctps": "Série CTPS",
            "func_esta_ctps": "Estado CTPS",
            "func_emis_ctps": "Emissão CTPS",
            "func_titu": "Título de Eleitor",
            "func_digi_titu": "Dígito Título",
            "func_zona_titu": "Zona Eleitoral",
            "func_seca_titu": "Seção Eleitoral",
            "func_regi_prof": "Registro Profissional",
            "func_regi_cate": "Categoria Registro Prof.",
            "func_regi_vali": "Validade Registro Prof.",
            "func_rege": "RG",
            "func_rege_orga": "Órgão Emissor RG",
            "func_rege_expe": "Expedição RG",
            "func_rege_uf": "UF RG",
            "func_cnh": "CNH",
            "func_cate": "Categoria CNH",
            "func_cnh_prim": "1ª Habilitação",
            "func_cnh_emis": "Emissão CNH",
            "func_cnh_vali": "Validade CNH",
            "func_cnh_esta": "Estado CNH",
            "func_rne": "RNE",
            "func_rne_emis": "Emissor RNE",
            "func_rne_expe": "Expedição RNE",
            "func_extr_cond": "Condição Estrangeiro",
            "func_extr_data_cheg": "Data Chegada ao Brasil",
            "func_extr_casa_bras": "Casado com Brasileiro(a)",
            "func_extr_filh_bras": "Filho(s) Brasileiro(s)",
            "func_defi": "Deficiência",
            "func_tipo_defi": "Tipo de Deficiência",
            "func_defi_cota": "Cota para Deficientes",
            # Jornada
            "func_en01": "Entrada 1",
            "func_sa01": "Saída 1",
            "func_en02": "Entrada 2",
            "func_sa02": "Saída 2",
            "func_saba": "Sábado",
            "func_domi": "Domingo",
            "func_feri": "Feriado",
            "func_dia1": "Dia 1 (férias)",
            "func_ven1": "Vencimento 1",
            "func_dia2": "Dia 2 (férias)",
            "func_ven2": "Vencimento 2",
            "func_temp_resi": "Tempo de Residência",
            # Saúde / Exames
            "func_venc_exam": "Vencimento do Exame",
            "func_exam_data": "Data do Exame",
            "func_exam_codi": "Código do Exame",
            "func_exam_cnpj": "CNPJ Clínica",
            "func_exam_crm": "CRM Médico",
            "func_exam_crm_uf": "UF CRM",
            "func_data_expi_exam_ocup": "Expiração Exame Ocupacional",
            "func_tipo_exam_ocup": "Tipo de Exame Ocupacional",
            # Estágio
            "func_esta_natu_esta": "Natureza do Estágio",
            "func_esta_nive_esta": "Nível do Estágio",
            "func_esta_data_term": "Término do Estágio",
            "func_esta_inst_ensi": "Instituição de Ensino",
            "func_apren_contr_dire": "Contrato Aprendizagem Direto",
            "func_apren_enti_qual": "Entidade Qualificadora",
            # eSocial
            "func_esoc_tipo_insc": "Tipo de Inscrição (eSocial)",
            "func_esoc_nume_insc": "Número de Inscrição (eSocial)",
            "func_esoc_matr_ante": "Matrícula Anterior (eSocial)",
            "func_esoc_tran_obse": "Observação Transmissão",
            "func_esoc_data_tran": "Data de Transmissão",
            "func_codi_lota_trib": "Código Lotação Tributária",
            "func_cate_tpinsc": "Tipo de Inscrição Categoria",
            "func_cate_nrinsc": "Nº Inscrição Categoria",
            "func_cons_fgts_inst": "Instituição FGTS",
            "func_cons_fgts_contr": "Contrato FGTS",
            "func_cons_fgts_even": "Evento FGTS",
        }

        widgets = {
            # Identificação
            "func_empr": forms.NumberInput(attrs=_ctrl("Empresa")),
            "func_fili": forms.NumberInput(attrs=_ctrl("Filial")),
            "func_codi": forms.NumberInput(attrs=_ctrl("Código")),
            "func_regi": forms.TextInput(attrs=_ctrl("Registro")),
            "func_nome": forms.TextInput(attrs=_ctrl("Nome Completo")),
            "func_sexo": forms.Select(choices=[("", "---------")] + SEXO_CHOICES, attrs={"class": "form-select"}),
            "func_dana": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_cpf": forms.TextInput(attrs=_ctrl("000.000.000-00", {"maxlength": "14"})),
            "func_pis": forms.TextInput(attrs=_ctrl("PIS/PASEP")),
            "func_esci": forms.Select(choices=[("", "---------")] + ESTADO_CIVIL_CHOICES, attrs={"class": "form-select"}),
            "func_naci": forms.TextInput(attrs=_ctrl("Código IBGE")),
            "func_raca": forms.TextInput(attrs=_ctrl("Raça/Cor")),
            "func_vinc": forms.TextInput(attrs=_ctrl("Vínculo")),
            "func_natu": forms.TextInput(attrs=_ctrl("Naturalidade")),
            "func_uf_natu": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            "func_pais_nasc": forms.TextInput(attrs=_ctrl("País de Nascimento")),
            "func_pais_naci": forms.TextInput(attrs=_ctrl("País de Nacionalidade")),
            "func_emai": forms.EmailInput(attrs=_ctrl("e-mail@exemplo.com")),
            "func_celu": forms.TextInput(attrs=_ctrl("(00) 00000-0000")),
            "func_fone_dive": forms.TextInput(attrs=_ctrl("Outros telefones")),
            "func_inat": forms.CheckboxInput(attrs=_check()),
            "func_apre": forms.CheckboxInput(attrs=_check()),
            # Endereço
            "func_tipo_logr": forms.TextInput(attrs=_ctrl("Rua / Av / Trav")),
            "func_ende": forms.TextInput(attrs=_ctrl("Endereço")),
            "func_bair": forms.TextInput(attrs=_ctrl("Bairro")),
            "func_cep": forms.TextInput(attrs=_ctrl("00000-000", {"maxlength": "9"})),
            "func_esta": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            "func_ibge": forms.TextInput(attrs=_ctrl("Código IBGE")),
            "func_loca": forms.TextInput(attrs=_ctrl("Cidade")),
            "func_loca_uf": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            # Vínculo
            "func_depa": forms.NumberInput(attrs=_ctrl("Departamento")),
            "func_seto": forms.NumberInput(attrs=_ctrl("Setor")),
            "func_carg": forms.NumberInput(attrs=_ctrl("Cargo")),
            "func_catr": forms.NumberInput(attrs=_ctrl("Categoria")),
            "func_daad": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_tiad": forms.NumberInput(attrs=_ctrl("Tipo")),
            "func_demi": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_tide": forms.NumberInput(attrs=_ctrl("Tipo")),
            "func_fopa": forms.Select(choices=[("", "---------")] + FOPA_CHOICES, attrs={"class": "form-select"}),
            "func_tisa": forms.TextInput(attrs=_ctrl("Tipo de Salário")),
            "func_tisa_rais": forms.TextInput(attrs=_ctrl("RAIS")),
            "func_cbo": forms.TextInput(attrs=_ctrl("CBO")),
            "func_grin": forms.TextInput(attrs=_ctrl("Grau de Instrução")),
            "func_cose": forms.TextInput(attrs=_ctrl("Código")),
            "func_sind": forms.NumberInput(attrs=_ctrl("Sindicato")),
            "func_func_sind": forms.CheckboxInput(attrs=_check()),
            "func_refe_desc_sind": forms.TextInput(attrs=_ctrl("Referência")),
            "func_tipo_cont": forms.NumberInput(attrs=_ctrl("Tipo")),
            "func_data_term_cont": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_esoc_tipo_admi": forms.NumberInput(attrs=_ctrl()),
            "func_esoc_indi_admi": forms.NumberInput(attrs=_ctrl()),
            "func_natu_ativ": forms.NumberInput(attrs=_ctrl()),
            "func_cate_esoc": forms.NumberInput(attrs=_ctrl()),
            "func_cate_sefi": forms.NumberInput(attrs=_ctrl()),
            "func_ocor_sefi": forms.NumberInput(attrs=_ctrl()),
            "func_matr": forms.NumberInput(attrs=_ctrl("Matrícula")),
            "func_norm": forms.NumberInput(attrs=_ctrl()),
            "func_jorn": forms.NumberInput(attrs=_ctrl("Horas")),
            "func_esoc_regi_jorn": forms.NumberInput(attrs=_ctrl()),
            "func_regi_prev": forms.NumberInput(attrs=_ctrl()),
            "func_apos": forms.CheckboxInput(attrs=_check()),
            "func_tp_rein": forms.NumberInput(attrs=_ctrl()),
            "func_num_proc": forms.TextInput(attrs=_ctrl("Nº do Processo")),
            "func_lei_anis": forms.TextInput(attrs=_ctrl("Lei")),
            "func_data_efet_reto": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_data_efeito": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_indi_contr": forms.NumberInput(attrs=_ctrl()),
            # Salário
            "func_home": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_hose": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_same": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_saho": forms.NumberInput(attrs=_ctrl("0.00000000", {"step": "0.00000001"})),
            "func_sala_cont": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_valo_diar": forms.NumberInput(attrs=_ctrl("0.00000000", {"step": "0.00000001"})),
            "func_pens": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_adqu": forms.CheckboxInput(attrs=_check()),
            "func_insa": forms.CheckboxInput(attrs=_check()),
            "func_peri": forms.CheckboxInput(attrs=_check()),
            "func_perc_insa": forms.NumberInput(attrs=_ctrl("%")),
            "func_insa_sobr": forms.NumberInput(attrs=_ctrl()),
            "func_insa_sobr_valo": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_base_insa": forms.NumberInput(attrs=_ctrl()),
            "func_alva": forms.NumberInput(attrs=_ctrl()),
            "func_vale_alim": forms.CheckboxInput(attrs=_check()),
            "func_vale_trans": forms.CheckboxInput(attrs=_check()),
            # Banco / Pagamento
            "func_banc_paga": forms.NumberInput(attrs=_ctrl("Código do Banco")),
            "func_agen": forms.TextInput(attrs=_ctrl("Agência")),
            "func_cont_paga": forms.TextInput(attrs=_ctrl("Conta")),
            "func_tipo_cred": forms.NumberInput(attrs=_ctrl()),
            "func_cont_fgts": forms.TextInput(attrs=_ctrl("Conta FGTS")),
            "func_daop_fgts": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_inss": forms.CheckboxInput(attrs=_check()),
            "func_fgts": forms.CheckboxInput(attrs=_check()),
            "func_irrf": forms.CheckboxInput(attrs=_check()),
            "func_remu_outr_tpinsc": forms.NumberInput(attrs=_ctrl()),
            "func_remu_outr_nrinsc": forms.TextInput(attrs=_ctrl()),
            "func_remu_outr_cate": forms.NumberInput(attrs=_ctrl()),
            "func_remu_outr_valo": forms.NumberInput(attrs=_ctrl("0.00", {"step": "0.01"})),
            "func_remu_outr_indi": forms.NumberInput(attrs=_ctrl()),
            # Documentos
            "func_ctps": forms.TextInput(attrs=_ctrl("CTPS")),
            "func_seri_ctps": forms.TextInput(attrs=_ctrl("Série")),
            "func_esta_ctps": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            "func_emis_ctps": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_titu": forms.TextInput(attrs=_ctrl("Título de Eleitor")),
            "func_digi_titu": forms.TextInput(attrs=_ctrl("Dígito")),
            "func_zona_titu": forms.TextInput(attrs=_ctrl("Zona")),
            "func_seca_titu": forms.TextInput(attrs=_ctrl("Seção")),
            "func_regi_prof": forms.TextInput(attrs=_ctrl("Registro")),
            "func_regi_cate": forms.TextInput(attrs=_ctrl("Categoria")),
            "func_regi_vali": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_rege": forms.TextInput(attrs=_ctrl("RG")),
            "func_rege_orga": forms.TextInput(attrs=_ctrl("SSP/PR")),
            "func_rege_expe": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_rege_uf": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            "func_cnh": forms.TextInput(attrs=_ctrl("CNH")),
            "func_cate": forms.TextInput(attrs=_ctrl("A/B/AB/C...")),
            "func_cnh_prim": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_cnh_emis": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_cnh_vali": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_cnh_esta": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            "func_rne": forms.TextInput(attrs=_ctrl("RNE")),
            "func_rne_emis": forms.TextInput(attrs=_ctrl("Emissor")),
            "func_rne_expe": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_extr_cond": forms.NumberInput(attrs=_ctrl()),
            "func_extr_data_cheg": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_extr_casa_bras": forms.CheckboxInput(attrs=_check()),
            "func_extr_filh_bras": forms.CheckboxInput(attrs=_check()),
            "func_defi": forms.TextInput(attrs=_ctrl("Deficiência")),
            "func_tipo_defi": forms.NumberInput(attrs=_ctrl()),
            "func_defi_cota": forms.CheckboxInput(attrs=_check()),
            # Jornada
            "func_en01": forms.TimeInput(attrs={**_ctrl(), "type": "time"}),
            "func_sa01": forms.TimeInput(attrs={**_ctrl(), "type": "time"}),
            "func_en02": forms.TimeInput(attrs={**_ctrl(), "type": "time"}),
            "func_sa02": forms.TimeInput(attrs={**_ctrl(), "type": "time"}),
            "func_saba": forms.NumberInput(attrs=_ctrl("Sábado")),
            "func_domi": forms.NumberInput(attrs=_ctrl("Domingo")),
            "func_feri": forms.NumberInput(attrs=_ctrl("Feriado")),
            "func_dia1": forms.NumberInput(attrs=_ctrl("Dia")),
            "func_ven1": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_dia2": forms.NumberInput(attrs=_ctrl("Dia")),
            "func_ven2": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_temp_resi": forms.NumberInput(attrs=_ctrl("Meses")),
            # Saúde / Exames
            "func_venc_exam": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_exam_data": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_exam_codi": forms.TextInput(attrs=_ctrl("Código")),
            "func_exam_cnpj": forms.TextInput(attrs=_ctrl("CNPJ")),
            "func_exam_crm": forms.TextInput(attrs=_ctrl("CRM")),
            "func_exam_crm_uf": forms.TextInput(attrs=_ctrl("UF", {"maxlength": "2"})),
            "func_data_expi_exam_ocup": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_tipo_exam_ocup": forms.NumberInput(attrs=_ctrl()),
            # Estágio
            "func_esta_natu_esta": forms.NumberInput(attrs=_ctrl()),
            "func_esta_nive_esta": forms.NumberInput(attrs=_ctrl()),
            "func_esta_data_term": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_esta_inst_ensi": forms.TextInput(attrs=_ctrl("CNPJ da Instituição")),
            "func_apren_contr_dire": forms.NumberInput(attrs=_ctrl()),
            "func_apren_enti_qual": forms.TextInput(attrs=_ctrl("CNPJ da Entidade")),
            # eSocial
            "func_esoc_tipo_insc": forms.NumberInput(attrs=_ctrl()),
            "func_esoc_nume_insc": forms.TextInput(attrs=_ctrl()),
            "func_esoc_matr_ante": forms.TextInput(attrs=_ctrl()),
            "func_esoc_tran_obse": forms.Textarea(attrs={**_ctrl(), "rows": "3"}),
            "func_esoc_data_tran": forms.DateInput(attrs={**_ctrl(), "type": "date"}),
            "func_codi_lota_trib": forms.TextInput(attrs=_ctrl()),
            "func_cate_tpinsc": forms.NumberInput(attrs=_ctrl()),
            "func_cate_nrinsc": forms.TextInput(attrs=_ctrl()),
            "func_cons_fgts_inst": forms.TextInput(attrs=_ctrl()),
            "func_cons_fgts_contr": forms.TextInput(attrs=_ctrl()),
            "func_cons_fgts_even": forms.NumberInput(attrs=_ctrl()),
        }