from django.db import models
from core.consultas import BancoConsulta


class Funcionarios(models.Model):
    registro = models.CharField(primary_key=True, max_length=14)
    func_empr = models.IntegerField()
    func_fili = models.IntegerField()
    func_codi = models.IntegerField()
    func_regi = models.CharField(max_length=30, blank=True, null=True)
    func_nome = models.CharField(max_length=60, blank=True, null=True)
    func_sexo = models.CharField(max_length=1, blank=True, null=True)
    func_dana = models.DateField(blank=True, null=True)
    func_cpf = models.CharField(max_length=11, blank=True, null=True)
    func_pis = models.CharField(max_length=11, blank=True, null=True)
    func_ende = models.CharField(max_length=60, blank=True, null=True)
    func_bair = models.CharField(max_length=60, blank=True, null=True)
    func_cep = models.CharField(max_length=8, blank=True, null=True)
    func_pai = models.CharField(max_length=60, blank=True, null=True)
    func_mae = models.CharField(max_length=60, blank=True, null=True)
    func_esci = models.CharField(max_length=1, blank=True, null=True)
    func_deir = models.IntegerField(blank=True, null=True)
    func_desa = models.IntegerField(blank=True, null=True)
    func_anch = models.CharField(max_length=4, blank=True, null=True)
    func_daad = models.DateField(blank=True, null=True)
    func_tiad = models.IntegerField(blank=True, null=True)
    func_demi = models.DateField(blank=True, null=True)
    func_tide = models.IntegerField(blank=True, null=True)
    func_tisa = models.CharField(max_length=1, blank=True, null=True)
    func_home = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_hose = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_same = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_saho = models.DecimalField(max_digits=15, decimal_places=8, blank=True, null=True)
    func_fopa = models.CharField(max_length=1, blank=True, null=True)
    func_adqu = models.BooleanField(blank=True, null=True)
    func_insa = models.BooleanField(blank=True, null=True)
    func_peri = models.BooleanField(blank=True, null=True)
    func_banc_paga = models.IntegerField(blank=True, null=True)
    func_cont_paga = models.CharField(max_length=11, blank=True, null=True)
    func_cont_fgts = models.CharField(max_length=11, blank=True, null=True)
    func_inss = models.BooleanField(blank=True, null=True)
    func_fgts = models.BooleanField(blank=True, null=True)
    func_irrf = models.BooleanField(blank=True, null=True)
    func_depa = models.IntegerField(blank=True, null=True)
    func_seto = models.IntegerField(blank=True, null=True)
    func_carg = models.IntegerField(blank=True, null=True)
    func_sind = models.IntegerField(blank=True, null=True)
    func_ibge = models.CharField(max_length=7, blank=True, null=True)
    func_grin = models.CharField(max_length=2, blank=True, null=True)
    func_cbo = models.CharField(max_length=6, blank=True, null=True)
    func_naci = models.CharField(max_length=2, blank=True, null=True)
    func_raca = models.CharField(max_length=1, blank=True, null=True)
    func_vinc = models.CharField(max_length=2, blank=True, null=True)
    func_ctps = models.CharField(max_length=11, blank=True, null=True)
    func_seri_ctps = models.CharField(max_length=5, blank=True, null=True)
    func_esta_ctps = models.CharField(max_length=2, blank=True, null=True)
    func_emis_ctps = models.DateField(blank=True, null=True)
    func_defi = models.CharField(max_length=1, blank=True, null=True)
    func_titu = models.CharField(max_length=14, blank=True, null=True)
    func_digi_titu = models.CharField(max_length=2, blank=True, null=True)
    func_zona_titu = models.CharField(max_length=5, blank=True, null=True)
    func_seca_titu = models.CharField(max_length=5, blank=True, null=True)
    func_regi_prof = models.CharField(max_length=20, blank=True, null=True)
    func_regi_cate = models.CharField(max_length=30, blank=True, null=True)
    func_regi_vali = models.DateField(blank=True, null=True)
    func_venc_exam = models.DateField(blank=True, null=True)
    func_sala_cont = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_tisa_rais = models.CharField(max_length=1, blank=True, null=True)
    func_cate_sefi = models.IntegerField(blank=True, null=True)
    func_ocor_sefi = models.IntegerField(blank=True, null=True)
    func_celu = models.CharField(max_length=14, blank=True, null=True)
    func_emai = models.CharField(max_length=100, blank=True, null=True)
    func_rege = models.CharField(max_length=15, blank=True, null=True)
    func_rege_orga = models.CharField(max_length=6, blank=True, null=True)
    func_rege_expe = models.DateField(blank=True, null=True)
    func_cnh = models.CharField(max_length=20, blank=True, null=True)
    func_cate = models.CharField(max_length=2, blank=True, null=True)
    func_cnh_prim = models.DateField(blank=True, null=True)
    func_cnh_emis = models.DateField(blank=True, null=True)
    func_cnh_vali = models.DateField(blank=True, null=True)
    func_daop_fgts = models.DateField(blank=True, null=True)
    func_esta = models.CharField(max_length=2, blank=True, null=True)
    func_foto = models.BinaryField(blank=True, null=True)
    func_cose = models.CharField(max_length=3, blank=True, null=True)
    func_alva = models.IntegerField(blank=True, null=True)
    func_pens = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_fone_dive = models.CharField(max_length=30, blank=True, null=True)
    func_dia1 = models.IntegerField(blank=True, null=True)
    func_ven1 = models.DateField(blank=True, null=True)
    func_dia2 = models.IntegerField(blank=True, null=True)
    func_ven2 = models.DateField(blank=True, null=True)
    func_refe_desc_sind = models.CharField(max_length=6, blank=True, null=True)
    func_en01 = models.TimeField(blank=True, null=True)
    func_sa01 = models.TimeField(blank=True, null=True)
    func_en02 = models.TimeField(blank=True, null=True)
    func_sa02 = models.TimeField(blank=True, null=True)
    func_func_sind = models.BooleanField(blank=True, null=True)
    func_tipo_defi = models.IntegerField(blank=True, null=True)
    func_catr = models.IntegerField(blank=True, null=True)
    func_data_cada = models.DateField(blank=True, null=True)
    func_data_alte = models.DateField(blank=True, null=True)
    func_norm = models.IntegerField(blank=True, null=True)
    func_saba = models.IntegerField(blank=True, null=True)
    func_domi = models.IntegerField(blank=True, null=True)
    func_feri = models.IntegerField(blank=True, null=True)
    func_rege_uf = models.CharField(max_length=2, blank=True, null=True)
    func_loca = models.CharField(max_length=30, blank=True, null=True)
    func_loca_uf = models.CharField(max_length=2, blank=True, null=True)
    func_regi_casa = models.IntegerField(blank=True, null=True)
    func_tipo_cred = models.IntegerField(blank=True, null=True)
    func_matr = models.IntegerField(blank=True, null=True)
    func_base_insa = models.IntegerField(blank=True, null=True)
    func_inat = models.BooleanField(blank=True, null=True)
    field_log_data = models.DateField(db_column='_log_data', blank=True, null=True)  # Field renamed because it started with '_'.
    field_log_time = models.TimeField(db_column='_log_time', blank=True, null=True)  # Field renamed because it started with '_'.
    func_apre = models.BooleanField(blank=True, null=True)
    func_agen = models.CharField(max_length=11, blank=True, null=True)
    func_nume = models.CharField(max_length=5, blank=True, null=True)
    func_comp = models.CharField(max_length=20, blank=True, null=True)
    func_perc_insa = models.IntegerField(blank=True, null=True)
    func_insa_sobr = models.IntegerField(blank=True, null=True)
    func_natu = models.CharField(max_length=60, blank=True, null=True)
    func_uf_natu = models.CharField(max_length=2, blank=True, null=True)
    func_exam_data = models.DateField(blank=True, null=True)
    func_exam_codi = models.CharField(max_length=17, blank=True, null=True)
    func_exam_cnpj = models.CharField(max_length=14, blank=True, null=True)
    func_exam_crm = models.CharField(max_length=10, blank=True, null=True)
    func_exam_crm_uf = models.CharField(max_length=2, blank=True, null=True)
    func_cate_esoc = models.IntegerField(blank=True, null=True)
    func_jorn = models.SmallIntegerField(blank=True, null=True)
    func_noso = models.CharField(max_length=60, blank=True, null=True)
    func_pais_nasc = models.CharField(max_length=7, blank=True, null=True)
    func_pais_naci = models.CharField(max_length=7, blank=True, null=True)
    func_rne = models.CharField(max_length=14, blank=True, null=True)
    func_rne_emis = models.CharField(max_length=20, blank=True, null=True)
    func_rne_expe = models.DateField(blank=True, null=True)
    func_cnh_esta = models.CharField(max_length=2, blank=True, null=True)
    func_tipo_logr = models.CharField(max_length=4, blank=True, null=True)
    func_extr_cond = models.IntegerField(blank=True, null=True)
    func_extr_data_cheg = models.DateField(blank=True, null=True)
    func_extr_casa_bras = models.BooleanField(blank=True, null=True)
    func_extr_filh_bras = models.BooleanField(blank=True, null=True)
    func_defi_cota = models.BooleanField(blank=True, null=True)
    func_apos = models.BooleanField(blank=True, null=True)
    func_esoc_tipo_admi = models.IntegerField(blank=True, null=True)
    func_esoc_indi_admi = models.IntegerField(blank=True, null=True)
    func_natu_ativ = models.IntegerField(blank=True, null=True)
    func_esoc_regi_jorn = models.IntegerField(blank=True, null=True)
    func_regi_prev = models.IntegerField(blank=True, null=True)
    func_tipo_cont = models.IntegerField(blank=True, null=True)
    func_data_term_cont = models.DateField(blank=True, null=True)
    func_cont_temp_parc = models.IntegerField(blank=True, null=True)
    func_codi_lota_trib = models.CharField(max_length=15, blank=True, null=True)
    func_insa_sobr_valo = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_esoc_tipo_insc = models.IntegerField(blank=True, null=True)
    func_esoc_nume_insc = models.CharField(max_length=15, blank=True, null=True)
    func_esoc_matr_ante = models.CharField(max_length=30, blank=True, null=True)
    func_esoc_tran_obse = models.CharField(max_length=255, blank=True, null=True)
    func_esoc_data_tran = models.DateField(blank=True, null=True)
    func_vale_alim = models.BooleanField(blank=True, null=True)
    func_valo_diar = models.DecimalField(max_digits=15, decimal_places=8, blank=True, null=True)
    func_cate_tpinsc = models.IntegerField(blank=True, null=True)
    func_cate_nrinsc = models.CharField(max_length=14, blank=True, null=True)
    func_temp_resi = models.IntegerField(blank=True, null=True)
    func_apren_contr_dire = models.IntegerField(blank=True, null=True)
    func_apren_enti_qual = models.CharField(max_length=14, blank=True, null=True)
    func_indi_contr = models.IntegerField(blank=True, null=True)
    func_esta_natu_esta = models.IntegerField(blank=True, null=True)
    func_esta_nive_esta = models.IntegerField(blank=True, null=True)
    func_esta_data_term = models.DateField(blank=True, null=True)
    func_esta_inst_ensi = models.CharField(max_length=14, blank=True, null=True)
    func_tp_rein = models.IntegerField(blank=True, null=True)
    func_num_proc = models.CharField(max_length=20, blank=True, null=True)
    func_lei_anis = models.CharField(max_length=13, blank=True, null=True)
    func_data_efet_reto = models.DateField(blank=True, null=True)
    func_data_efeito = models.DateField(blank=True, null=True)
    func_cons_fgts_inst = models.CharField(max_length=3, blank=True, null=True)
    func_cons_fgts_contr = models.CharField(max_length=15, blank=True, null=True)
    func_remu_outr_tpinsc = models.IntegerField(blank=True, null=True)
    func_remu_outr_nrinsc = models.CharField(max_length=14, blank=True, null=True)
    func_remu_outr_cate = models.IntegerField(blank=True, null=True)
    func_remu_outr_valo = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    func_remu_outr_indi = models.IntegerField(blank=True, null=True)
    func_cons_fgts_even = models.IntegerField(blank=True, null=True)
    func_cons_fgts_inst2 = models.CharField(max_length=3, blank=True, null=True)
    func_cons_fgts_contr2 = models.CharField(max_length=12, blank=True, null=True)
    func_cons_fgts_even2 = models.IntegerField(blank=True, null=True)
    func_cons_fgts_even3 = models.IntegerField(blank=True, null=True)
    func_cons_fgts_contr3 = models.CharField(max_length=12, blank=True, null=True)
    func_cons_fgts_inst3 = models.CharField(max_length=3, blank=True, null=True)
    func_cons_fgts_even4 = models.IntegerField(blank=True, null=True)
    func_cons_fgts_inst4 = models.CharField(max_length=3, blank=True, null=True)
    func_cons_fgts_contr4 = models.CharField(max_length=12, blank=True, null=True)
    func_data_expi_exam_ocup = models.DateField(blank=True, null=True)
    func_tipo_exam_ocup = models.IntegerField(blank=True, null=True)
    func_vale_trans = models.BooleanField(blank=True, null=True)

    objects = BancoConsulta()
    class Meta:
        managed = False
        db_table = 'funcionarios'
        unique_together = (('registro', 'func_empr', 'func_codi'),)