from django.db import models
from core.consultas import BancoConsulta

class Empresas(models.Model):
    empr_empr = models.IntegerField()
    empr_fili = models.IntegerField()
    empr_nome = models.CharField(max_length=200, blank=True, null=True)
    empr_fant = models.CharField(max_length=200, blank=True, null=True)
    empr_cnpj = models.CharField(max_length=14, blank=True, null=True)
    empr_insc_esta = models.CharField(max_length=25, blank=True, null=True)
    empr_insc_muni = models.CharField(max_length=25, blank=True, null=True)
    empr_cpf = models.CharField(max_length=11, blank=True, null=True)
    empr_cei = models.CharField(max_length=12, blank=True, null=True)
    empr_nire = models.CharField(max_length=11, blank=True, null=True)
    empr_data_nire = models.DateField(blank=True, null=True)
    empr_cep = models.CharField(max_length=8, blank=True, null=True)
    empr_ende = models.CharField(max_length=120, blank=True, null=True)
    empr_nume = models.CharField(max_length=10, blank=True, null=True)
    empr_comp = models.CharField(max_length=20, blank=True, null=True)
    empr_bair = models.CharField(max_length=60, blank=True, null=True)
    empr_ibge = models.CharField(max_length=7, blank=True, null=True)
    empr_cida = models.CharField(max_length=60, blank=True, null=True)
    empr_esta = models.CharField(max_length=2, blank=True, null=True)
    empr_fone_empr = models.CharField(max_length=14, blank=True, null=True)
    empr_emai_empr = models.CharField(max_length=200, blank=True, null=True)
    empr_celu_cont = models.CharField(max_length=14, blank=True, null=True)
    empr_nome_cont = models.CharField(max_length=60, blank=True, null=True)
    empr_emai_cont = models.CharField(max_length=200, blank=True, null=True)
    empr_regi_trib = models.IntegerField(blank=True, null=True)
    empr_cont_ipi = models.IntegerField(blank=True, null=True)
    empr_perf_empr = models.CharField(max_length=1, blank=True, null=True)
    empr_ativ_empr = models.IntegerField(blank=True, null=True)
    empr_tipo_ecd = models.CharField(max_length=5, blank=True, null=True)
    empr_host_prox = models.CharField(max_length=100, blank=True, null=True)
    empr_senh_prox = models.CharField(max_length=50, blank=True, null=True)
    empr_port_prox = models.CharField(max_length=15, blank=True, null=True)
    empr_usua_prox = models.CharField(max_length=100, blank=True, null=True)
    empr_host_smtp = models.CharField(max_length=100, blank=True, null=True)
    empr_port_smtp = models.CharField(max_length=15, blank=True, null=True)
    empr_usua_smtp = models.CharField(max_length=100, blank=True, null=True)
    empr_senh_smtp = models.CharField(max_length=100, blank=True, null=True)
    empr_ssl_smtp = models.BooleanField(blank=True, null=True)
    empr_tls_smtp = models.BooleanField(blank=True, null=True)
    empr_obse = models.TextField(blank=True, null=True)
    empr_apre_na_entr = models.BooleanField(blank=True, null=True)
    empr_logo_empr = models.BinaryField(blank=True, null=True)
    empr_logo_pref = models.BinaryField(blank=True, null=True)
    field_log_data = models.DateField(db_column='_log_data', blank=True, null=True)  # Field renamed because it started with '_'.   
    field_log_time = models.TimeField(db_column='_log_time', blank=True, null=True)  # Field renamed because it started with '_'.   
    empr_soci_1 = models.IntegerField(blank=True, null=True)
    empr_soci_2 = models.IntegerField(blank=True, null=True)
    empr_qual_soci_1 = models.IntegerField(blank=True, null=True)
    empr_qual_soci_2 = models.IntegerField(blank=True, null=True)
    empr_assi_1 = models.BooleanField(blank=True, null=True)
    empr_assi_2 = models.BooleanField(blank=True, null=True)
    empr_cont = models.IntegerField(blank=True, null=True)
    empr_qual_cont = models.IntegerField(blank=True, null=True)
    empr_ambi_nfe = models.IntegerField(blank=True, null=True)
    empr_cert_nfe = models.CharField(max_length=30, blank=True, null=True)
    empr_senh_cert_nfe = models.CharField(max_length=30, blank=True, null=True)
    empr_ambi_nfc = models.IntegerField(blank=True, null=True)
    empr_cert_nfc = models.CharField(max_length=30, blank=True, null=True)
    empr_senh_cert_nfc = models.CharField(max_length=30, blank=True, null=True)
    empr_ambi_nfs = models.IntegerField(blank=True, null=True)
    empr_cert_nfs = models.CharField(max_length=30, blank=True, null=True)
    empr_senh_cert_nfs = models.CharField(max_length=30, blank=True, null=True)
    empr_ambi_cte = models.IntegerField(blank=True, null=True)
    empr_cert_cte = models.CharField(max_length=30, blank=True, null=True)
    empr_senh_cert_cte = models.CharField(max_length=30, blank=True, null=True)
    empr_cnae = models.CharField(max_length=10, blank=True, null=True)
    empr_desc_cnae = models.TextField(blank=True, null=True)
    empr_subs_st = models.IntegerField(blank=True, null=True)
    empr_lote_nfe = models.IntegerField(blank=True, null=True)
    empr_lote_even_nfe = models.IntegerField(blank=True, null=True)
    empr_lote_cte = models.IntegerField(blank=True, null=True)
    empr_lote_even_cte = models.IntegerField(blank=True, null=True)
    empr_lote_serv = models.IntegerField(blank=True, null=True)
    empr_lote_even_serv = models.IntegerField(blank=True, null=True)
    registro = models.CharField(primary_key=True, max_length=14)
    empr_teso = models.IntegerField(blank=True, null=True)
    empr_paga_mes = models.BooleanField(blank=True, null=True)
    empr_rat = models.DecimalField(max_digits=2, decimal_places=1, blank=True, null=True)
    empr_fpas = models.IntegerField(blank=True, null=True)
    empr_codi_outr_enti = models.IntegerField(blank=True, null=True)
    empr_codi_gps = models.IntegerField(blank=True, null=True)
    empr_isen_fila = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    empr_inat = models.SmallIntegerField(blank=True, null=True)
    empr_tipo_empr = models.IntegerField(blank=True, null=True)
    empr_naju = models.CharField(max_length=4, blank=True, null=True)
    empr_nupr = models.IntegerField(blank=True, null=True)
    empr_daba = models.DateField(blank=True, null=True)
    empr_data_alte_soci_1 = models.DateField(blank=True, null=True)
    empr_nsu = models.CharField(max_length=50, blank=True, null=True)
    empr_data_alte_soci_2 = models.DateField(blank=True, null=True)
    empr_simp_naci_anex = models.IntegerField(blank=True, null=True)
    empr_data_aber = models.DateField(blank=True, null=True)
    empr_tipo_apur_lucr_real = models.IntegerField(blank=True, null=True)
    empr_cont_trab = models.TextField(blank=True, null=True)
    
    objects = BancoConsulta()   
    
    class Meta:
        managed = False
        db_table = 'empresas'
        unique_together = (('registro', 'empr_empr', 'empr_fili'),)# Create your models here.