from django.db import models    
from core.consultas import BancoConsulta

class Ferias(models.Model):
    registro = models.CharField(primary_key=True, max_length=14)
    feri_empr = models.IntegerField()
    feri_func = models.IntegerField()
    feri_refe = models.CharField(max_length=6)
    feri_sequ = models.IntegerField()
    feri_data_avis = models.DateField(blank=True, null=True)
    feri_data_reci = models.DateField(blank=True, null=True)
    feri_data_paga = models.DateField(blank=True, null=True)
    feri_medi_hora = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_medi_valo = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_sala_mens = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_sala_hora = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_aqui_inic = models.DateField(blank=True, null=True)
    feri_aqui_fina = models.DateField(blank=True, null=True)
    feri_falt = models.IntegerField(blank=True, null=True)
    feri_novo_aqui_inic = models.DateField(blank=True, null=True)
    feri_novo_aqui_fina = models.DateField(blank=True, null=True)
    feri_feri_inic = models.DateField(blank=True, null=True)
    feri_feri_fina = models.DateField(blank=True, null=True)
    feri_dias_feri = models.IntegerField(blank=True, null=True)
    feri_abon_inic = models.DateField(blank=True, null=True)
    feri_abon_fina = models.DateField(blank=True, null=True)
    feri_dias_abon = models.IntegerField(blank=True, null=True)
    feri_dias_sala_1 = models.IntegerField(blank=True, null=True)
    feri_sala_refe_1 = models.CharField(max_length=6, blank=True, null=True)
    feri_dias_sala_2 = models.IntegerField(blank=True, null=True)
    feri_sala_refe_2 = models.CharField(max_length=6, blank=True, null=True)
    feri_deci_terc = models.BooleanField(blank=True, null=True)
    feri_obse = models.TextField(blank=True, null=True)
    field_log_data = models.DateField(db_column='_log_data', blank=True, null=True)  # Field renamed because it started with '_'.   
    field_log_time = models.TimeField(db_column='_log_time', blank=True, null=True)  # Field renamed because it started with '_'.   
    feri_refe_folh = models.CharField(max_length=6, blank=True, null=True)
    feri_feri_base_refe_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_feri_valo_refe_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_terc_valo_refe_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_feri_base_refe_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_feri_valo_refe_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_terc_valo_refe_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_base_inss_refe_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_base_inss_refe_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_inss_refe_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_inss_refe_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_base_irrf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_irrf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_faix_irrf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_depe_irrf = models.IntegerField(blank=True, null=True)
    feri_base_abon_pecu = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_abon_pecu = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_medi_valo = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_medi_hora = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_mese_medi = models.IntegerField(blank=True, null=True)
    feri_terc_abon_pecu = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_deci_terc = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_aliq_fgts = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_fgts_deci = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_medi_valo_deci = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_valo_medi_hora_deci = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_adic_temp_serv_ferias = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_adic_temp_serv_13feri = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_adic_temp_serv_ferias2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_adic_temp_serv_13feri2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_peri_valo_refe_1 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_peri_valo_refe_2 = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_pens_alim = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_base_pens_alim = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_desc_empr_cons = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_base_desc_empr_cons = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    feri_grat_valo = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    
    objects = BancoConsulta()      

    class Meta:
        managed = False
        db_table = 'ferias'
        unique_together = (('registro', 'feri_empr', 'feri_func', 'feri_refe', 'feri_sequ'),)

# Create your models here.
