# Generated by Django 2.2.28 on 2026-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folhamensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fome_empr', models.IntegerField()),
                ('fome_fili', models.IntegerField()),
                ('fome_func', models.IntegerField()),
                ('fome_refe', models.CharField(max_length=6)),
                ('fome_even', models.IntegerField()),
                ('fome_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fome_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fome_valo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fome_faix', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fome_desa', models.IntegerField(blank=True, null=True)),
                ('fome_deir', models.IntegerField(blank=True, null=True)),
                ('fome_tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('fome_tipo_base', models.CharField(blank=True, max_length=5, null=True)),
                ('fome_orde_clas', models.CharField(blank=True, max_length=10, null=True)),
                ('fome_data_paga', models.DateField(blank=True, null=True)),
                ('fome_refe_prox_paga', models.CharField(blank=True, max_length=6, null=True)),
                ('fome_depa', models.IntegerField(blank=True, null=True)),
                ('fome_seto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'folhamensal',
                'managed': False,
            },
        ),
    ]
